export default `302	Klima und Biodiversität				Mehr Forschungsbudget für Ökolandbau		Nur 2% des Agrarforschungsbudgets gehen an den Bereich Ökolandbau. Dabei ist dieser Bereich essentiell, um die Klimaziele zu erreichen.
345	Soziale Gerechtigkeit				Bürger*innendividende - Fortschritt & Teilhabe		Statt einiger weniger könnten alle von der Digitalisierung von Arbeit profitieren. Die Bürger*innendividende fordert genau das! Fortschritt ja! Aber zugunsten aller, nicht weniger.
28	Klima und Biodiversität				Permakultur und Agroforst ohne Bürokratiewahnsinn		Permakultur und Agroforstsysteme sind gut fürs Klima und fürs Ökosystem. Lasst uns die bürokratischen Hürden für Bäuer*innen senken, dass sie Unterstützung bei der Umsetzung erhalten.
172	Klima und Biodiversität				Gebäude brauchen Klimaschutzgesetze!		Gebäude verursachen viele Treibhausgase. Wir brauchen ein Klimaschutzgesetz für Gebäude, dass das 1,5°C-Ziel möglich macht.
104	Klima und Biodiversität				CO2-Steuer an echte Kosten anpassen!		Die CO2-Steuer soll auf 180€ pro Tonne erhöht werden. Der eingenommene Betrag soll teilweise als Klimaprämie an die privaten Haushalte zurückgezahlt werden.
177	Klima und Biodiversität				Expressbusse durch City-Maut		Städte und Gemeinden sollen eine City-Maut erheben dürfen, um den ÖPNV-Ausbau zu beschleunigen.
166	Demokratie				Bundesweite Bürger*innenbeteiligung und direkte Demokratie		Stabsstelle auf Bundesebene für Bürger*innenbeteiligung und direkte Demokratie. Diese Stabsstelle soll u.a. Möglichkeiten der Partizipation für die Bürger*innen bekanntmachen.
185	Demokratie				Bürger*innenrat für nationale Klimapolitik		Ein Bürger*innenrat soll über folgende Frage beraten: Wie kann Deutschland bis 2030 seine Treibhausgasemissionen um mindestens 55% verringern, unter Berücksichtigung von sozialer Gerechtigkeit?
71	Zeit nach Corona				Unternehmensziel SINN, staatlich gefördert		Deutschland soll sich auf EU-Ebene für neue Wege der Unternehmensfinanzierung einsetzen, um kooperatives Wirtschaften im Dienst des Gemeinwohls, der Natur und des allgemeinen Bedarfs zu fördern.
342	Zeit nach Corona				Trillions4FUTURE - Coronahilfen sozial, ökologisch einsetzen		Die Vergabe von Coronahilfen soll an strenge soziale und ökologische Nachhaltigkeitskriterien geknüpft werden.
319	Zeit nach Corona				Neue Rechtsform: PURPOSE-Unternehmen		Neue Rechtsform für Unternehmen, die ihre langfristige Unabhängigkeit und Werteorientierung rechtlich bindend sichern wollen. Sinnmaximierung statt Shareholder-Value-Optimierung.
314	Zeit nach Corona				Neben Wachstum auch Gemeinwohl als Staatsziel		Der Erfolg eines Staates braucht mehr Messgrößen als nur das Bruttoinlandsprodukt (BIP). Das BIP soll um Gemeinwohl-Aspekte erweitert werden, z.B. das Wohlbefinden der Bevölkerung.
306	Klima und Biodiversität				Job ohne Zukunft? GRUNDEINKOMMEN JETZT!		Arbeitnehmer*innen in nicht-zukunftsfähigen Branchen sollen Anrecht auf ein Grundeinkommen für 3 Jahre erhalten. Menschen, die von notwendigem Strukturwandel betroffen wären, bekämen Wertschätzung und Zeit für Neuorientierung.
174	Soziale Gerechtigkeit				Barrierefreiheit und Teilhabe als Pflicht für privaten Sektor		Der private Sektor soll barrierefrei gestaltet werden, um Menschen mit Behinderungen die Teilhabe an der Wirtschaft vollständig zu ermöglichen.
307	Zeit nach Corona				Kurzarbeit und Teilzeit PLUS als Recht		Arbeitnehmer*innen in Kurzarbeit sollen die Möglichkeit erhalten, diese auf 18 Monate auszuweiten. Angestellte sollen bis zu 3 Jahre in Teilzeit Plus arbeiten können.
299	Klima und Biodiversität				Verbot von Mikroplastik in Kosmetika!		 Der gesundheitliche Schaden von Mikroplastik kann zum jetzigen Zeitpunkt nicht ausgeschlossen werden. Kosmetika, die Mikroplastik enthalten, sollen verboten werden.
346	Klima und Biodiversität				Landwirtschaft ist einer DER Klimahebel, Agrarwende jetzt!		Um die Klimaziele zu erreichen, müssen wir die Landwirtschaft neu gestalten. Die Umstellung auf Agroforstsysteme soll erleichtert und Agroforst-Landwirt*innen gefördert werden.
77	Klima und Biodiversität				Recht auf Reparatur statt Neukauf!		In Deutschland produzierte und gehandelte Produkte sollen ein "Recht auf Reparatur" erhalten. Das bedeute, dass Produkte so konzipiert werden, dass eine Reparatur möglich ist.
240	Soziale Gerechtigkeit				Kindesmissbrauch, Häusliche Gewalt und Femizide stoppen!		Programm, dass die Fallzahlen von (sexualisierter) Gewalt an Kindern und Frauen drastisch verringert. Aufklärung, Beratungsstellen und Prävention MÜSSEN Teil unserer Gesellschaft werden.
267	Soziale Gerechtigkeit				#fairbylaw - Sorgfaltspflicht per Gesetz für Unternehmen		Unternehmen sollen für Umwelt und Menschenrechtsverletzungen haftbar gemacht werden, auch wenn sie ihre unternehmerische Sorgfaltspflicht im Ausland vernachlässigen.
143	Demokratie				Direkte Demokratie und losbasierte Bürgerräte auf Bundesebene		Der Bundestag wird aufgefordert, eine Kombination von losbasierten Bürgerräten und bundesweiten Volksbegehren einzuführen.
298	Soziale Gerechtigkeit				Antirassismus & Bekenntnis zu Deutschland als Einwanderungsland ins Grundgesetz
190	Kilma und Biodiversität				Bau/Stadtentwicklung Nachhaltigkeit`;
